<a href="https://colab.research.google.com/github/leotagliati/AulasComp/blob/main/Hands_on_DataCleaning_20260402.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Valores Ausentes

In [ ]:
import seaborn as sns
import pandas as pd

df = sns.load_dataset('titanic')
display(df.head())

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
print("Valores ausentes por coluna:")
display(df.isnull().sum())

Valores ausentes por coluna:

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [ ]:
df_dropped = df.dropna()

print("Shape do DataFrame original:", df.shape)
print("Shape do DataFrame após remover linhas com valores ausentes:", df_dropped.shape)
print("Valores ausentes após dropna():")
display(df_dropped.isnull().sum())

Shape do DataFrame original: (891, 15)
Shape do DataFrame após remover linhas com valores ausentes: (182, 15)
Valores ausentes após dropna():

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
deck           0
embark_town    0
alive          0
alone          0
dtype: int64

## Identificando linhas

In [ ]:
df = sns.load_dataset('titanic')

In [ ]:
df[ df.isnull().any(axis=1) ]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

## Preenchendo Valores (Imputação)

In [ ]:
df_filled = df.copy()

df_filled['age'] = df_filled['age'].fillna(df_filled['age'].mean())

df_filled['embarked'] = df_filled['embarked'].fillna(df_filled['embarked'].mode()[0])

df_filled['deck'] = df_filled['deck'].cat.add_categories('Unknown')
df_filled['deck'] = df_filled['deck'].fillna('Unknown')

print("Valores ausentes após preencher (imputação):")
display(df_filled.isnull().sum())

Valores ausentes após preencher (imputação):

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
deck           0
embark_town    2
alive          0
alone          0
dtype: int64

In [ ]:
import numpy as np

df = pd.DataFrame(np.random.standard_normal((7, 3)))

df.iloc[:4, 1] = np.nan
df.iloc[:2, 2] = np.nan

df

          0         1         2
0  1.136355       NaN       NaN
1 -2.653462       NaN       NaN
2  0.821479       NaN -1.116735
3 -0.328148       NaN  0.475061
4 -0.040658 -0.766069 -0.331947
5  0.430141  0.926767 -0.302135
6 -0.880557  2.140791 -0.726645

In [ ]:
df.fillna(0)

          0         1         2
0  1.136355  0.000000  0.000000
1 -2.653462  0.000000  0.000000
2  0.821479  0.000000 -1.116735
3 -0.328148  0.000000  0.475061
4 -0.040658 -0.766069 -0.331947
5  0.430141  0.926767 -0.302135
6 -0.880557  2.140791 -0.726645

In [ ]:
df.fillna({1: 0.5, 2: 0})

          0         1         2
0  1.136355  0.500000  0.000000
1 -2.653462  0.500000  0.000000
2  0.821479  0.500000 -1.116735
3 -0.328148  0.500000  0.475061
4 -0.040658 -0.766069 -0.331947
5  0.430141  0.926767 -0.302135
6 -0.880557  2.140791 -0.726645

In [ ]:
# df.fillna(method="ffill") # wesmckinney

df.bfill()

          0         1         2
0  1.136355 -0.766069 -1.116735
1 -2.653462 -0.766069 -1.116735
2  0.821479 -0.766069 -1.116735
3 -0.328148 -0.766069  0.475061
4 -0.040658 -0.766069 -0.331947
5  0.430141  0.926767 -0.302135
6 -0.880557  2.140791 -0.726645

In [ ]:
df.iloc[0,1] = 0

df.interpolate()

          0         1         2
0  1.136355  0.000000       NaN
1 -2.653462 -0.191517       NaN
2  0.821479 -0.383035 -1.116735
3 -0.328148 -0.574552  0.475061
4 -0.040658 -0.766069 -0.331947
5  0.430141  0.926767 -0.302135
6 -0.880557  2.140791 -0.726645

# Transformação, Mapping, Replace

In [ ]:
df = sns.load_dataset('titanic')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
# Cria um dicionário de mapeamento
class_mapping = {
    1: 'First Class',
    2: 'Second Class',
    3: 'Third Class'
}

# Aplica a função `map` à coluna 'pclass' para criar 'class_description'
df['class_description'] = df['pclass'].map(class_mapping)
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,class_description
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,Third Class
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,First Class
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,Third Class
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,First Class
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,Third Class

In [ ]:
df['gender_numeric'] = df['sex'].replace({'male': 0, 'female': 1})

display(df[['sex', 'gender_numeric']].head())

/tmp/ipykernel_3270/2928746567.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['gender_numeric'] = df['sex'].replace({'male': 0, 'female': 1})

      sex  gender_numeric
0    male               0
1  female               1
2  female               1
3  female               1
4    male               0

In [ ]:
df.loc[:,'gender_numeric'].replace(0,np.nan,inplace=True)
display(df[['sex', 'gender_numeric']].head())

      sex  gender_numeric
0    male             NaN
1  female             1.0
2  female             1.0
3  female             1.0
4    male             NaN

# Discretização

In [ ]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,class_description,gender_numeric
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,Third Class,NaN
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,First Class,1.0
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,Third Class,1.0
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,First Class,1.0
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,Third Class,NaN

In [ ]:
pd.cut(df.age, 4).value_counts()

age
(20.315, 40.21]    385
(0.34, 20.315]     179
(40.21, 60.105]    128
(60.105, 80.0]      22
Name: count, dtype: int64

In [ ]:
pd.cut(df.age, [0, 18, 40, 60]).value_counts()

age
(18, 40]    425
(0, 18]     139
(40, 60]    128
Name: count, dtype: int64

In [ ]:
df['age_category'] = pd.cut(df.age, [0, 18, 40, 60])
df[['survived','age','age_category']].head()

   survived   age age_category
0         0  22.0     (18, 40]
1         1  38.0     (18, 40]
2         1  26.0     (18, 40]
3         1  35.0     (18, 40]
4         0  35.0     (18, 40]

In [ ]:
df[['survived','age','age_category']].dtypes

survived           int64
age              float64
age_category    category
dtype: object

In [ ]:
bins = [0, 18, 40, 60]
group_names = ["Youth", "YoungAdult", "Senior"]

pd.cut(df.age, bins, labels=group_names)

0      YoungAdult
1      YoungAdult
2      YoungAdult
3      YoungAdult
4      YoungAdult
          ...
886    YoungAdult
887    YoungAdult
888           NaN
889    YoungAdult
890    YoungAdult
Name: age, Length: 891, dtype: category
Categories (3, object): ['Youth' < 'YoungAdult' < 'Senior']

In [ ]:
pd.qcut(df.age, 4, labels=['Q1', 'Q2', 'Q3', 'Q4'])

0       Q2
1       Q3
2       Q2
3       Q3
4       Q3
      ...
886     Q2
887     Q1
888    NaN
889     Q2
890     Q3
Name: age, Length: 891, dtype: category
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

# Dados categóricos

In [ ]:
df = sns.load_dataset('titanic')
display(df.head())

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
# Cria um dicionário de mapeamento
class_mapping = {
    1: 'First Class',
    2: 'Second Class',
    3: 'Third Class'
}

# Aplica a função `map` à coluna 'pclass' para criar 'class_description'
df['class_description'] = df['pclass'].map(class_mapping)
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,class_description,gender_numeric,age_category
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,Third Class,NaN,"(18, 40]"
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,First Class,1.0,"(18, 40]"
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,Third Class,1.0,"(18, 40]"
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,First Class,1.0,"(18, 40]"
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,Third Class,NaN,"(18, 40]"

In [ ]:
df.dtypes

survived                int64
pclass                  int64
sex                    object
age                   float64
sibsp                   int64
parch                   int64
fare                  float64
embarked               object
class                category
who                    object
adult_male               bool
deck                 category
embark_town            object
alive                  object
alone                    bool
class_description      object
gender_numeric        float64
age_category         category
dtype: object

In [ ]:
df['class'].cat.categories

Index(['First', 'Second', 'Third'], dtype='object')

In [ ]:
%%script echo skip
df.loc[0,'class'] = 'Third Class'

skip

In [ ]:
 df['class'].cat.categories

Index(['First', 'Second', 'Third'], dtype='object')

In [ ]:
df['class'] = df['class'].cat.add_categories(['Unknow']) # não é in-place
df.loc[0,'class'] = 'Unknow'
df.loc[1,'class'] = np.nan

df.loc[0:1,'class']

0    Unknow
1       NaN
Name: class, dtype: category
Categories (4, object): ['First', 'Second', 'Third', 'Unknow']

In [ ]:
category_order = ['Third Class', 'Second Class', 'First Class']

df['class_description'] = pd.Categorical(df['class_description'], categories=category_order, ordered=True)

df['class_description'] = df['class'].map({'First': 'First Class', 'Second': 'Second Class', 'Third': 'Third Class'})

df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,class_description,gender_numeric,age_category
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,Third Class,NaN,"(18, 40]"
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,First Class,1.0,"(18, 40]"
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,Third Class,1.0,"(18, 40]"
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,First Class,1.0,"(18, 40]"
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,Third Class,NaN,"(18, 40]"

In [ ]:
df['class'] = df['class'].astype('str')
df['class']

0      Unknow
1         nan
2       Third
3       First
4       Third
        ...
886    Second
887     First
888     Third
889     First
890     Third
Name: class, Length: 891, dtype: object

In [ ]:
df['class'] = df['class'].astype('category')
df['class']

0      Unknow
1         nan
2       Third
3       First
4       Third
        ...
886    Second
887     First
888     Third
889     First
890     Third
Name: class, Length: 891, dtype: category
Categories (5, object): ['First', 'Second', 'Third', 'Unknow', 'nan']

In [ ]:
df['class'].str.len()

0      6
1      3
2      5
3      5
4      5
      ..
886    6
887    5
888    5
889    5
890    5
Name: class, Length: 891, dtype: int64

# Mais sobre expressões regulares

In [ ]:
import pandas as pd
import numpy as np
import re

data = {
    'name': [
        "  João Silva ", "Maria_Souza", "Pedro-Oliveira", "Ana Costa",
        "Luiz Santos", "Fernanda G. Almeida", "Carlos A. H. Eduardo", "Julia Dias",
        "Rafael Martins", "Beatriz Lima"
    ],
    'state_code': [
        "SP", "RJ", "MG", "ES", "BA ", "rJ", "SPP", "mg",
        "AM", "DF"
    ],
    'state_name': [
        "São Paulo", "Rio de Janeiro", "Minas Gerais", "Espirito Santo",
        "Bahia", "Rio de janeir0", "São pAUlo", "Minas Geraes",
        "Amazonas", "Distrito Federal"
    ],
    'nasc': [
        "1990-01-15", "1985/03/22", "05-10-1992", "1991.07.30",
        "1988/12/01", "02/29/1996", "1999-11-05", "1987-04-18",
        "2000-08-23", "1993-06-10"
    ]
}
df = pd.DataFrame(data)
display(df)

                   name state_code        state_name        nasc
0           João Silva          SP         São Paulo  1990-01-15
1           Maria_Souza         RJ    Rio de Janeiro  1985/03/22
2        Pedro-Oliveira         MG      Minas Gerais  05-10-1992
3             Ana Costa         ES    Espirito Santo  1991.07.30
4           Luiz Santos        BA              Bahia  1988/12/01
5   Fernanda G. Almeida         rJ    Rio de janeir0  02/29/1996
6  Carlos A. H. Eduardo        SPP         São pAUlo  1999-11-05
7            Julia Dias         mg      Minas Geraes  1987-04-18
8        Rafael Martins         AM          Amazonas  2000-08-23
9          Beatriz Lima         DF  Distrito Federal  1993-06-10

## `findall`

In [ ]:
df['nasc_digits'] = df['nasc'].str.findall(r'\d+')

display(df[['nasc', 'nasc_digits']].head())

         nasc     nasc_digits
0  1990-01-15  [1990, 01, 15]
1  1985/03/22  [1985, 03, 22]
2  05-10-1992  [05, 10, 1992]
3  1991.07.30  [1991, 07, 30]
4  1988/12/01  [1988, 12, 01]

In [ ]:
df['nasc_digits_1st'] = df['nasc'].str.findall(r'\d+').str[0]

display(df[['nasc', 'nasc_digits_1st']].head())

         nasc nasc_digits_1st
0  1990-01-15            1990
1  1985/03/22            1985
2  05-10-1992              05
3  1991.07.30            1991
4  1988/12/01            1988

In [ ]:
df['name_initials'] = df['name'].str.findall(r'\b[A-Z]\.')
display(df[['name', 'name_initials']])

                   name name_initials
0           João Silva             []
1           Maria_Souza            []
2        Pedro-Oliveira            []
3             Ana Costa            []
4           Luiz Santos            []
5   Fernanda G. Almeida          [G.]
6  Carlos A. H. Eduardo      [A., H.]
7            Julia Dias            []
8        Rafael Martins            []
9          Beatriz Lima            []

In [ ]:
df.loc[6,['name_initials']].to_list()[0][0]

'A'

## `match`

In [ ]:
df['name_starts_with_J'] = df['name'].str.match(r'^J', na=False)
display(df[['name', 'name_starts_with_J']][df['name_starts_with_J'] == True])

         name  name_starts_with_J
7  Julia Dias                True

## Padronizando datas

In [ ]:
# Padronizar formato de data para 'YYYY-MM-DD'
def standardize_date(date_str):
    if pd.isna(date_str): # Handle potential NaN values
        return np.nan
    match = re.match(r'(\d{4})[-/.](\d{2})[-/.](\d{2})', date_str) # YYYY-MM-DD or YYYY/MM/DD or YYYY.MM.DD
    if match:
        return f"{match.group(1)}-{match.group(2)}-{match.group(3)}"
    match = re.match(r'(\d{2})[-/.](\d{2})[-/.](\d{4})', date_str) # DD-MM-YYYY or DD/MM/YYYY or DD.MM.YYYY
    if match:
        return f"{match.group(3)}-{match.group(2)}-{match.group(1)}"
    return date_str # Return original if no pattern matches

df['nasc_standardized'] = df['nasc'].apply(standardize_date)
display(df[['nasc', 'nasc_standardized']])

         nasc nasc_standardized
0  1990-01-15        1990-01-15
1  1985/03/22        1985-03-22
2  05-10-1992        1992-10-05
3  1991.07.30        1991-07-30
4  1988/12/01        1988-12-01
5  02/29/1996        1996-29-02
6  1999-11-05        1999-11-05
7  1987-04-18        1987-04-18
8  2000-08-23        2000-08-23
9  1993-06-10        1993-06-10